// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8hYyWwjuceTDCQ2Vx9MMQ8DKpzLg50-c',
    appId: '1:980895016848:web:e92f36d4af16d946f87515',
    messagingSenderId: '980895016848',
    projectId: 'ai-generator-app-a507c',
    authDomain: 'ai-generator-app-a507c.firebaseapp.com',
    storageBucket: 'ai-generator-app-a507c.firebasestorage.app',
    measurementId: 'G-DGFKSJ1SB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6hO4xNp7Lxdzqbwi-zAF0iygcpqqYtsY',
    appId: '1:980895016848:android:1c507ea122647bb3f87515',
    messagingSenderId: '980895016848',
    projectId: 'ai-generator-app-a507c',
    storageBucket: 'ai-generator-app-a507c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4pZ17kMWmIE2DbFwfX2VUTRnSqx3R2FA',
    appId: '1:980895016848:ios:813e18300c5fd64df87515',
    messagingSenderId: '980895016848',
    projectId: 'ai-generator-app-a507c',
    storageBucket: 'ai-generator-app-a507c.firebasestorage.app',
    iosBundleId: 'com.example.aiGeneratorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4pZ17kMWmIE2DbFwfX2VUTRnSqx3R2FA',
    appId: '1:980895016848:ios:813e18300c5fd64df87515',
    messagingSenderId: '980895016848',
    projectId: 'ai-generator-app-a507c',
    storageBucket: 'ai-generator-app-a507c.firebasestorage.app',
    iosBundleId: 'com.example.aiGeneratorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8hYyWwjuceTDCQ2Vx9MMQ8DKpzLg50-c',
    appId: '1:980895016848:web:1efde646ae46dd15f87515',
    messagingSenderId: '980895016848',
    projectId: 'ai-generator-app-a507c',
    authDomain: 'ai-generator-app-a507c.firebaseapp.com',
    storageBucket: 'ai-generator-app-a507c.firebasestorage.app',
    measurementId: 'G-745MBFBGS9',
  );
}
